// This file is automatically generated. Do not edit it directly.
import { createClient } from "@supabase/supabase-js";
import type { Database } from "./types";

const SUPABASE_URL = "https://qzwxisdfwswsrbzvpzlo.supabase.co";
const SUPABASE_ANON_KEY =
  "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InF6d3hpc2Rmd3N3c3JienZwemxvIiwicm9sZSI6ImFub24iLCJpYXQiOjE3Mzg1OTg2NjYsImV4cCI6MjA1NDE3NDY2Nn0.nVV1d-_BfhfVNOSiusg8zSuvPwS4dSB-cJAMGVjujr4";
/**
 * Check if we're running on a production BuntingGPT domain
 */
function isProductionHost(hostname: string): boolean {
  return hostname === "buntinggpt.com" || hostname.endsWith(".buntinggpt.com");
}

const isProductionDomain = typeof window !== "undefined" && isProductionHost(window.location.hostname);

/**
 * Cookie chunking configuration
 * Large JWTs exceed cookie size limits, so we split into chunks
 */
const COOKIE_CHUNK_SIZE = 3000;
const COOKIE_MAX_AGE = 60 * 60 * 24 * 7; // 7 days

/**
 * Cookie-based storage for cross-subdomain session sharing
 * Uses `.buntinggpt.com` domain to share sessions across all subdomains
 */
const cookieStorage = {
  getItem: (key: string): string | null => {
    try {
      const cookies = document.cookie.split("; ");
      const chunks: { index: number; value: string }[] = [];

      for (const cookie of cookies) {
        const [cookieKey, ...valueParts] = cookie.split("=");
        const cookieValue = valueParts.join("=");

        if (cookieKey.startsWith(`${key}_chunk_`)) {
          const indexStr = cookieKey.substring(`${key}_chunk_`.length);
          const index = parseInt(indexStr, 10);
          if (!isNaN(index)) {
            chunks.push({ index, value: decodeURIComponent(cookieValue) });
          }
        }
      }

      if (chunks.length === 0) return null;
      chunks.sort((a, b) => a.index - b.index);
      return chunks.map((c) => c.value).join("") || null;
    } catch (e) {
      console.error("[Cookie] Read error:", e);
      return null;
    }
  },

  setItem: (key: string, value: string): void => {
    try {
      // Clear existing chunks first
      cookieStorage.removeItem(key);

      // Split value into chunks
      const chunks: string[] = [];
      for (let i = 0; i < value.length; i += COOKIE_CHUNK_SIZE) {
        chunks.push(value.substring(i, i + COOKIE_CHUNK_SIZE));
      }

      // Write each chunk as a separate cookie
      chunks.forEach((chunk, index) => {
        const chunkKey = `${key}_chunk_${index}`;
        const encodedChunk = encodeURIComponent(chunk);
        // CRITICAL: Cookie domain must include leading dot for subdomain sharing
        document.cookie = `${chunkKey}=${encodedChunk}; path=/; domain=.buntinggpt.com; max-age=${COOKIE_MAX_AGE}; SameSite=Lax; Secure`;
      });
    } catch (e) {
      console.error("[Cookie] Write error:", e);
    }
  },

  removeItem: (key: string): void => {
    try {
      const cookies = document.cookie.split("; ");
      for (const cookie of cookies) {
        const [cookieKey] = cookie.split("=");
        if (cookieKey.startsWith(`${key}_chunk_`)) {
          // Clear cookie by setting max-age to 0
          document.cookie = `${cookieKey}=; path=/; domain=.buntinggpt.com; max-age=0`;
        }
      }
    } catch (e) {
      console.error("[Cookie] Remove error:", e);
    }
  },
};

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    // Use cookies on production domains for cross-subdomain sharing
    // Fall back to localStorage for development
    storage: isProductionDomain ? cookieStorage : window.localStorage,
    persistSession: true,
    autoRefreshToken: true,
    detectSessionInUrl: true,
    flowType: "pkce",
  },
});
